export const SIDEBAR_ITEMS = [
    // Questionnaire components
    'form-tag',
    'section-tag',
    'field-tag',
    'information-tag',
    'table-tag',
    'table-field-tag',
    // Basic components
    'list-box-tag',
    'multi-select-tag',
    'radio-buttons-tag',
    'text-box-tag',
    'notes-tag',
    'date-tag',
    // Clinical Form specific components
    'cf-textbox-tag',
    'cf-textarea-tag',
    'cf-radio-tag',
    'cf-list-tag',
    'cf-check-tag',
    'cf-date-tag',
    'cf-button-tag',
    'cf-info-tag',
    'cf-group-tag',
    'cf-panel-tag',
    'cf-table-tag',
    'cf-notes-tag',
];

export const DRAG_TYPES = {
    // Questionnaire types
    'form-tag': 'page',
    'section-tag': 'question',
    'field-tag': 'field',
    'information-tag': 'information',
    'table-tag': 'table',
    'table-field-tag': 'table-field',
    // Basic Question components
    'list-box-tag': 'question',
    'multi-select-tag': 'question',
    'radio-buttons-tag': 'question',
    // Basic Field components
    'text-box-tag': 'field',
    'notes-tag': 'field',
    'date-tag': 'field',
    // Clinical Form types
    'cf-textbox-tag': 'cf-textbox',
    'cf-textarea-tag': 'cf-textarea',
    'cf-radio-tag': 'cf-radio',
    'cf-list-tag': 'cf-list',
    'cf-check-tag': 'cf-check',
    'cf-date-tag': 'cf-date',
    'cf-button-tag': 'cf-button',
    'cf-info-tag': 'cf-info',
    'cf-group-tag': 'cf-group',
    'cf-panel-tag': 'cf-panel',
    'cf-table-tag': 'cf-table',
    'cf-notes-tag': 'cf-notes',
};

export const VALIDATION_RULES = {
    // Questionnaire validation rules
    root: ['page'],
    page: ['question', 'field', 'information', 'table'],
    question: [], // Questions should not contain other items - they have their own answers
    field: [],
    information: [],
    table: ['table-field'],
    'table-field': [],

    // Clinical Form validation rules (based on XSD schema)
    'cf-root': ['cf-group', 'cf-panel', 'cf-table', 'cf-textbox', 'cf-textarea', 'cf-radio', 'cf-list', 'cf-check', 'cf-date', 'cf-button', 'cf-info', 'cf-notes'],
    'cf-group': ['cf-group', 'cf-panel', 'cf-table', 'cf-textbox', 'cf-textarea', 'cf-radio', 'cf-list', 'cf-check', 'cf-date', 'cf-button', 'cf-info', 'cf-notes'],
    'cf-panel': ['cf-group', 'cf-panel', 'cf-table', 'cf-textbox', 'cf-textarea', 'cf-radio', 'cf-list', 'cf-check', 'cf-date', 'cf-button', 'cf-info', 'cf-notes'],
    'cf-table': ['cf-group', 'cf-panel', 'cf-table', 'cf-textbox', 'cf-textarea', 'cf-radio', 'cf-list', 'cf-check', 'cf-date', 'cf-button', 'cf-info', 'cf-notes'],
    'cf-textbox': [],
    'cf-textarea': [],
    'cf-radio': [],
    'cf-list': [],
    'cf-check': [],
    'cf-date': [],
    'cf-button': [],
    'cf-info': [],
    'cf-notes': [],
};

export const DEFAULT_ITEMS = {
    // Questionnaire default items
    page: {
        type: 'page',
        label: 'Page',
        children: [],
    },
    question: {
        type: 'question',
        label: 'Question',
        children: [],
        dataType: 'List Box',
        textRecord: '',
        keyField: '',
        required: false,
        answers: [{ text: 'Option 1' }],
    },
    field: {
        type: 'field',
        label: 'Field',
        children: [],
        dataType: 'Text Box',
        keyField: '',
        required: false,
    },
    information: {
        type: 'information',
        label: 'New Information',
        children: [],
    },
    table: {
        type: 'table',
        label: 'New Table',
        children: [],
        keyField: '',
        required: false,
        columns: [
            { header: 'Column 1', dataType: 'Text Box', required: false },
        ],
    },
    'table-field': {
        type: 'table-field',
        label: 'New Table Field',
        children: [],
        dataType: 'Text Box',
        required: false,
    },

    // Clinical Form default items (based on XSD schema)
    'cf-textbox': {
        type: 'cf-textbox',
        label: 'Text Box',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
    },
    'cf-textarea': {
        type: 'cf-textarea',
        label: 'Text Area',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
    },
    'cf-radio': {
        type: 'cf-radio',
        label: 'Radio Button',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
        items: [{ text: 'Option 1', code: '1' }],
    },
    'cf-list': {
        type: 'cf-list',
        label: 'List',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
        items: [{ text: 'Option 1', code: 1 }],
    },
    'cf-check': {
        type: 'cf-check',
        label: 'Checkbox',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
    },
    'cf-date': {
        type: 'cf-date',
        label: 'Date',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
    },
    'cf-button': {
        type: 'cf-button',
        label: 'Button',
        children: [],
        text: 'Button',
        action: '',
    },
    'cf-info': {
        type: 'cf-info',
        label: 'Information',
        children: [],
        content: 'Information text',
        bind: '',
        show: '',
    },
    'cf-group': {
        type: 'cf-group',
        label: 'Group',
        children: [],
        title: 'Group Title',
        show: '',
    },
    'cf-panel': {
        type: 'cf-panel',
        label: 'Panel',
        children: [],
        title: 'Panel Title',
        show: '',
    },
    'cf-table': {
        type: 'cf-table',
        label: 'Table',
        children: [],
        name: '',
        required: false,
        show: '',
    },
    'cf-notes': {
        type: 'cf-notes',
        label: 'Notes',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
    },
};

export const COMPONENT_SPECIFIC_ITEMS = {
    // Questionnaire component-specific items
    'list-box-tag': {
        type: 'question',
        label: 'List Box',
        children: [],
        dataType: 'List Box',
        textRecord: '',
        keyField: '',
        required: false,
        answers: [{ text: 'Option 1' }],
    },
    'multi-select-tag': {
        type: 'question',
        label: 'Multi Select',
        children: [],
        dataType: 'Multi Select',
        textRecord: '',
        keyField: '',
        required: false,
        answers: [{ text: 'Option 1' }],
    },
    'radio-buttons-tag': {
        type: 'question',
        label: 'Radio Buttons',
        children: [],
        dataType: 'Radio Buttons',
        textRecord: '',
        keyField: '',
        required: false,
        answers: [{ text: 'Option 1' }],
    },
    'text-box-tag': {
        type: 'field',
        label: 'Text Box',
        children: [],
        dataType: 'Text Box',
        keyField: '',
        required: false,
    },
    'notes-tag': {
        type: 'field',
        label: 'Notes',
        children: [],
        dataType: 'Text Area',
        keyField: '',
        required: false,
    },
    'date-tag': {
        type: 'field',
        label: 'Date',
        children: [],
        dataType: 'Date',
        keyField: '',
        required: false,
    },

    // Clinical Form component-specific items
    'cf-textbox-tag': {
        type: 'cf-textbox',
        label: 'Text Box',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
        maxlength: null,
    },
    'cf-textarea-tag': {
        type: 'cf-textarea',
        label: 'Text Area',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
        maxlength: null,
    },
    'cf-radio-tag': {
        type: 'cf-radio',
        label: 'Radio Button',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
        items: [{ text: 'Option 1', code: '1' }],
    },
    'cf-list-tag': {
        type: 'cf-list',
        label: 'List',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
        items: [{ text: 'Option 1', code: 1 }],
    },
    'cf-check-tag': {
        type: 'cf-check',
        label: 'Checkbox',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
        checked: false,
    },
    'cf-date-tag': {
        type: 'cf-date',
        label: 'Date',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
    },
    'cf-button-tag': {
        type: 'cf-button',
        label: 'Button',
        children: [],
        text: 'Click Me',
        action: '',
        enabled: true,
    },
    'cf-info-tag': {
        type: 'cf-info',
        label: 'Information',
        children: [],
        content: 'Information text here',
        bind: '',
        show: '',
    },
    'cf-group-tag': {
        type: 'cf-group',
        label: 'Group',
        children: [],
        title: 'Group Title',
        show: '',
        enabled: true,
    },
    'cf-panel-tag': {
        type: 'cf-panel',
        label: 'Panel',
        children: [],
        title: 'Panel Title',
        show: '',
    },
    'cf-table-tag': {
        type: 'cf-table',
        label: 'Table',
        children: [],
        name: '',
        required: false,
        show: '',
    },
    'cf-notes-tag': {
        type: 'cf-notes',
        label: 'Notes',
        children: [],
        name: '',
        required: false,
        bind: '',
        show: '',
        global: false,
    },
};
